#!/bin/sh
#
# .git/hooks/post-commit
#

if [ -a .commit ]
	then
	rm .commit
	find . -name "*.build" -exec sh -c "echo `date '+%s'` > {}" \;
	git add *.build
	git commit --amend -C HEAD --no-verify
fi
